fix build

diff --git a/.gitea/workflows/deploy-native.yml b/.gitea/workflows/deploy-native.yml
--- a/.gitea/workflows/deploy-native.yml
+++ b/.gitea/workflows/deploy-native.yml
@@ -81,15 +81,15 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Login to registry
-        env:
-          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
-          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
-        run: |
-          export DOCKER_API_VERSION=1.43
-          test -n "${REGISTRY_USER:-}" || { echo "Missing secret REGISTRY_USER"; exit 1; }
-          test -n "${REGISTRY_PASSWORD:-}" || { echo "Missing secret REGISTRY_PASSWORD"; exit 1; }
-          echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$REGISTRY_USER" --password-stdin
+#      - name: Login to registry
+#        env:
+#          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
+#          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
+#        run: |
+#          export DOCKER_API_VERSION=1.43
+#          test -n "${REGISTRY_USER:-}" || { echo "Missing secret REGISTRY_USER"; exit 1; }
+#          test -n "${REGISTRY_PASSWORD:-}" || { echo "Missing secret REGISTRY_PASSWORD"; exit 1; }
+#          echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$REGISTRY_USER" --password-stdin
 
       - name: Pull and run
         env:
